#ifndef MSPCOM_H_
#define MSPCOM_H_

#define WVWMS_PORT 3001
#define WVWMS_COMMAND_PORT 3000

#define FRAME_START_1 0x7A
#define FRAME_START_2 0xA7

// MSP - ARM commands
#define CMD_MEASUREMENT 0x0B
#define CMD_MEAS_FAST 0xBB
#define CMD_MEAS_SAMPLE_PACK 0xBC
#define CMD_MEAS_CUTOFF 0xBD
#define CMD_MEAS_CUTOFF_PACK 0xBE
#define CMD_MEAS_PEAK 0xBF
#define CMD_MEAS_PEAK_SIMPLE 0xC0
#define CMD_MEAS_TRUCK	0xC1
#define CMD_MEAS_TRUCK_SIMPLE 0xC2  
#define CMD_READ_CONFIG 0x0C
#define CMD_WRITE_CONFIG 0x0D
#define CMD_LOAD_CONFIG_FLASH 0x0E
#define CMD_SAVE_CONFIG_FLASH 0x0F
#define CMD_WRITE_REGISTER 0x11
#define CMD_READ_REGISTER 0x12
#define CMD_ADC_TO_ARM 0x13
#define CMD_ARM_TO_ADC 0x14
#define CMD_GET_STATUS_REG 0x15
#define CMD_CONSOLE_PRINT 0x16
#define CMD_VAA_POWER 0x17
#define CMD_VDD_POWER 0x00
#define CMD_MODE 0x18
#define CMD_CALIBRATE 0x19
#define CMD_SOFT_RESET_ADC 0x1A
#define CMD_SELECT_CHANNEL 0x1B
#define CMD_MEASURE_BUFFER 0x1C
#define CMD_RANGE_SETUP	0x1D
#define CMD_ADC_POWER_MODE 0x1E
#define CMD_ADC_POWER 0x1F
#define CMD_CHECK_ADC 0x20
#define CMD_GET_ADC_TEMP 0x21
#define CMD_ADC_SINGLE 0x22
#define CMD_SET_CUTOFF 0x23
#define CMD_SET_ACX	0x24
#define CMD_SET_CHOP 0x25
#define CMD_SET_DEFAULT 0x26
#define CMD_SET_PEAK_SAMPLE 0x27
#define CMD_SET_BUFFER_SIZE 0x28

#define DATA_PACK 0xF0

#define CMD_REPLY 0xFF
#define REPLY_OK 0x00
#define ERROR_CODE_UNKNOWN_CMD 0x01
#define ERROR_CODE_IDLE 0x02
#define ERROR_CODE_FAILED 0x03
#define ERROR_WRONG_PARAM 0x04
#define ERROR_UNEXPECTD_ISR 0x05
#define ERROR_FLASH_KEY 0x06
#define ERROR_ADC_ID 0x07
#define PEAK_ACTIVE 0x08

#define IDLE_MODE 0x2
#define POWER_DOWN_MODE 0x3
#define INTERNAL_ZERO_SCALE 0x4
#define INTERNAL_FULL_SCALE 0x5
#define SYSTEM_ZERO_SCALE 0x6
#define SYSTEM_FULL_SCALE 0x7

#define G_5V 0
#define G_625mV 3
#define G_312mV  4
#define G_156mV 5
#define G_78mV 6
#define G_39mV 7 


#endif /* MSPCOM_H_ */
